name: Build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: [ '1.14', '1.15' ]

    name: Go ${{ matrix.go }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go get -v .

      - name: Run tests
        run: go test -coverprofile profile.cov

      - name: Run linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.24

      - name: Build examples
        run: cd _examples && go get -v .

      - name: Run examples tests
        run: cd _examples && go test

      - name: Send coverage report
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
